name = "ElmerCircuitBuilder"
uuid = "b2eb2500-c1b3-4ff4-bde2-8d492f01056f"
authors = ["gwlagerweij "]
version = "0.1.0"

[deps]
Elmer = "7d1d0d61-b954-47ad-902e-083a93170a02"

[compat]
Elmer = "0.1.0"
